$(document).ready(function(){
    $.getJSON('./api/amazon/search/mens%20clothing')
        .success(function(data){
            console.log(data);
        })
        .error(function(error){
            console.log('error:');
            console.log(error);
        });
    $.getJSON('./api/amazon/lookup/B00KOIBN9A')
        .success(function(data){
            console.log(data);
        })
        .error(function(error){
            console.log('error:');
            console.log(error);
        });
});